/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Slider_Lista;

import javax.swing.DefaultListModel;

/**
 *
 * @author acer
 */
public class tela_main extends javax.swing.JFrame {

    /**
     * Creates new form tela_main
     */
    public tela_main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        spin_inicio = new javax.swing.JSlider();
        spin_passo = new javax.swing.JSlider();
        spin_fim = new javax.swing.JSlider();
        lbl_inicio = new javax.swing.JLabel();
        lbl_passo = new javax.swing.JLabel();
        lbl_fim = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lista_item = new javax.swing.JList<>();
        btn_an = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Inicio");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Passo");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Fim");

        spin_inicio.setMaximum(5);
        spin_inicio.setValue(0);
        spin_inicio.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spin_inicioStateChanged(evt);
            }
        });

        spin_passo.setMaximum(4);
        spin_passo.setMinimum(1);
        spin_passo.setValue(1);
        spin_passo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spin_passoStateChanged(evt);
            }
        });

        spin_fim.setMaximum(20);
        spin_fim.setMinimum(6);
        spin_fim.setValue(6);
        spin_fim.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spin_fimStateChanged(evt);
            }
        });

        lbl_inicio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_inicio.setText("0");

        lbl_passo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_passo.setText("0");

        lbl_fim.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_fim.setText("0");

        lista_item.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lista_item.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        lista_item.setVisibleRowCount(10);
        jScrollPane1.setViewportView(lista_item);

        btn_an.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_an.setText("Listar");
        btn_an.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_anActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(spin_fim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(24, 24, 24)
                                    .addComponent(spin_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(18, 18, 18)
                                    .addComponent(spin_passo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_fim)
                            .addComponent(lbl_inicio)
                            .addComponent(lbl_passo)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(btn_an)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(lbl_inicio)
                            .addComponent(spin_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(spin_fim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_fim))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(spin_passo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_passo))
                        .addGap(32, 32, 32)
                        .addComponent(btn_an))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void spin_inicioStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spin_inicioStateChanged
        int num_ini = spin_inicio.getValue();
        lbl_inicio.setText(Integer.toString(num_ini));
    }//GEN-LAST:event_spin_inicioStateChanged

    private void spin_fimStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spin_fimStateChanged
        int num_fim = spin_fim.getValue();
        lbl_fim.setText(Integer.toString(num_fim));
    }//GEN-LAST:event_spin_fimStateChanged

    private void spin_passoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spin_passoStateChanged
        int num_passo = spin_passo.getValue();
        lbl_passo.setText(Integer.toString(num_passo));
    }//GEN-LAST:event_spin_passoStateChanged

    private void btn_anActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_anActionPerformed
        int num_ini = spin_inicio.getValue();
        int num_fim = spin_fim.getValue();
        int num_passo = spin_passo.getValue();
        
        DefaultListModel lista = new DefaultListModel();
        
        for(int c = num_ini;c<=num_fim;c+=num_passo){
            lista.addElement(c);
        }
        
        lista_item.setModel(lista);
    }//GEN-LAST:event_btn_anActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tela_main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_an;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_fim;
    private javax.swing.JLabel lbl_inicio;
    private javax.swing.JLabel lbl_passo;
    private javax.swing.JList<String> lista_item;
    private javax.swing.JSlider spin_fim;
    private javax.swing.JSlider spin_inicio;
    private javax.swing.JSlider spin_passo;
    // End of variables declaration//GEN-END:variables
}
